### ISSUE TITLE
Error is raised after we updated servers to ruby 3.3.5

### ISSUE THREAD

**Issue by egpotter** [Nu-hin/remote_ruby#3]
We are getting an exception whenever trying to use remote ruby since the server was upated to Ruby 3.3.5 .

```
/home/giscedu/.rvm/gems/ruby-3.3.5/gems/remote_ruby-0.2.1/lib/remote_ruby/runner.rb:37:in `run': undefined method `[]' for nil (NoMethodError)

      { result: locals[:__return_val__], locals: locals }
                      ^^^^^^^^^^^^^^^^^
	from /home/giscedu/.rvm/gems/ruby-3.3.5/gems/remote_ruby-0.2.1/lib/remote_ruby/execution_context.rb:102:in `execute_code'
	from /home/giscedu/.rvm/gems/ruby-3.3.5/gems/remote_ruby-0.2.1/lib/remote_ruby/execution_context.rb:34:in `execute'
	from ./scripts/make_ready_for_reactivation:18:in `<main>
```

I investigated a bit, and compared and noticed that in the Runner class, the read_stream is always getting EOF when reading from the outstream. The line `if line.start_with?('%%%MARSHAL')` is never reached, causing the locals to not be set and raising the error. Still could not find a solution, unfortunately.

**Comment by romuloceccon** [comment]
It's caused by https://github.com/rubygems/rubygems/commit/076aba8b1c25291a986f9c233cb80192adbe2fcf.

Related issue: https://github.com/rubygems/rubygems/issues/8106

Depending on the environment bundle will attempt to re-exec the ruby process with the correct bundler version in the gemset. But since the program is read from stdin, which is not seekable, the re-exec'ed process cannot load it. Hence the "line ... is never reached".

**Comment by Nu-hin** [comment]
Fixed by 03c420e337d519362cb57dfd1086c40cb7027da3 in #4.

Thanks @romuloceccon and @egpotter.

**Comment by Nu-hin** [comment]
See also: rubygems/rubygems#8329
